---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
  namespace: default
spec:
  secretName: local-example-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.mintdynastyresearch.org"
  dnsNames:
  - "local.mintdynastyresearch.org"
  - "*.local.mintdynastyresearch.org"
